### ISSUE TITLE
hard to compile on macos.

### ISSUE THREAD

**Issue by icepic** [Aransentin/DeiMOS#2]
homebrew defaulted to zig 0.15, which gives this error,
```install
└─ install deimos
   └─ compile exe deimos ReleaseFast native
      └─ run exe test_index_gen (test_indices.zig)
         └─ compile exe test_index_gen ReleaseFast native 1 errors
src/test_index_gen.zig:5:30: error: root source file struct 'process' has no member named 'Init'
pub fn main(init: std.process.Init) !void {
                  ~~~~~~~~~~~^~~~~
/opt/homebrew/Cellar/zig/0.15.2_1/lib/zig/std/process.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    comptime: /opt/homebrew/Cellar/zig/0.15.2_1/lib/zig/std/start.zig:61:51
    start: /opt/homebrew/Cellar/zig/0.15.2_1/lib/zig/std/std.zig:110:27
    1 reference(s) hidden; use '-freference-trace=3' to see all references
error: the following command failed with 1 compilation errors:
/opt/homebrew/Cellar/zig/0.15.2_1/bin/zig build-exe -fsingle-threaded -OReleaseFast -Mroot=/Users/jj/src/git/DeiMOS/src/test_index_gen.zig --cache-dir .zig-cache --global-cache-dir /Users/jj/.cache/zig --name test_index_gen --zig-lib-dir /opt/homebrew/Cellar/zig/0.15.2_1/lib/zig/ --listen=-
````
I found that some of that error is due to deprecated things in zig 0.15 according to https://ziggit.dev/t/cross-platform-main-zig-std-process-init/14318/3
so I downgraded to zig 0.14, but that led to a lot of macos 26.4 problems with the Xcode it comes with, which is a lot of lines like these:
```
 zig build -Doptimize=ReleaseFast 
error: undefined symbol: __availability_version_check
    note: referenced by /Users/jj/.cache/zig/o/0d213a4dbc4ac0ae44e4cba1d09032aa/libcompiler_rt.a(libcompiler_rt.a.o):___isPlatformVersionAtLeast
error: undefined symbol: _abort
    note: referenced by /Users/jj/src/git/DeiMOS/.zig-cache/o/673ca21af63969b6a2794336d668d805/build.o:_posix.abort
error: undefined symbol: _arc4random_buf
    note: referenced by /Users/jj/src/git/DeiMOS/.zig-cache/o/673ca21af63969b6a2794336d668d805/build.o:_crypto.tlcsprng.tlsCsprngFill
```

I guess one can downgrade Xcode and "fix" this, but perhaps the std.process.Init should be moved to how it is meant to work in zig 0.15.

**Comment by icepic** [comment]
Thank you, I'll spin up a VM and run it there. When/if you need macos testers, I'll be available.
